version: '3'
services:
  frontend: 
    build:
      dockerfile: Dockerfile.dev
      context: ./medlem
    volumes:
      - /app/node_modules
      - ./medlem:/app
    ports:
      - "3003:5173"
  server:
    build:
      dockerfile: Dockerfile.dev
      context: ./backend
    volumes:
      - /app/node_modules
      - ./backend:/app
    ports:
      - "5000:5000"
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80"
    depends_on:
      - frontend
      - server
